services:
  - type: web
    name: podcast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 2
    envVars:
      - key: OPENAI_API_KEY
        sync: false
